//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rush_App.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserEvents = new HashSet<UserEvent>();
        }
    
        public int ID { get; set; }
        public int UniversityID { get; set; }
        public string FirstName { get; set; }
        public string Major { get; set; }
        public Nullable<double> GPA { get; set; }
        public string Hometown { get; set; }
        public string HomeState { get; set; }
        public Nullable<int> GreekID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string LastName { get; set; }
        public string Year { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
    
        public virtual House House { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEvent> UserEvents { get; set; }
    }
}
